### ISSUE TITLE
Gnome 3.20.x & 3.21 support (Deprecated `St.Table` & stylesheet selectors)

### ISSUE THREAD

**Issue by romgrk** [awamper/howdoi#4]
Hello @awamper :)

You might be happy to learn that switching to `St.BoxLayout` is really trivial. I have been able to manage most of it on my local version with 

``` zsh
sed -i 's/St.Table/St.BoxLayout/' **.js
```

and some styling. (About styles, watch out for the 3.20: https://bugzilla.gnome.org/show_bug.cgi?id=765433)

But really it's just a repeat of https://github.com/awamper/howdoi/issues/3, as the issue is mostly the same. 

I also had a question, last commit is 10 months ago, are you maintaining this? (Otherwise, do you accept PRs for version updates?)

**Comment by awamper** [comment]
PRs are welcome.
3.20 - 1d9a6b6d240b8
